### ISSUE TITLE
Log spam from missing mob spawn amounts list

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsUtility#128]
![image](https://user-images.githubusercontent.com/15698722/157039294-e736169d-eb41-4245-8914-94f06c7f74f1.png)

The line `[Server thread/ERROR] [mcjtylib/]: The mob spawn amounts list for mob thermal:basalz is missing!` is pushed to the console for every tick that a Basalz Syringe is in the spawner. Originally this issue was just going to be that you can't spawn Basalz, but the log spam is really more important.

rftoolsutility-1.16-3.1.11
FTBTeam/FTB-Modpack-Issues/issues/638

**Comment by McJty** [comment]
Well that means there is some misconfiguration there

**Comment by aaronhowser1** [comment]
I don't see anything in the config or serverconfig for rftools utility about this

**Comment by McJty** [comment]
Hmm it must be there. Can you show me?

**Comment by aaronhowser1** [comment]
This is the entire block for the spawner in the rftoolsutility-server serverconfig:

```toml
#Settings for the spawner system
[spawner]
	#Maximum amount of injections we need to do a full mob extraction.
	#Range: > 1
	maxMobInjections = 10
```
